#pragma once

// From glfw3.h
#define MIST_MOUSE_BUTTON_1 0
#define MIST_MOUSE_BUTTON_2 1
#define MIST_MOUSE_BUTTON_3 2
#define MIST_MOUSE_BUTTON_4 3
#define MIST_MOUSE_BUTTON_5 4
#define MIST_MOUSE_BUTTON_6 5
#define MIST_MOUSE_BUTTON_7 6
#define MIST_MOUSE_BUTTON_8 7
#define MIST_MOUSE_BUTTON_LAST MIST_MOUSE_BUTTON_8
#define MIST_MOUSE_BUTTON_LEFT MIST_MOUSE_BUTTON_1
#define MIST_MOUSE_BUTTON_RIGHT MIST_MOUSE_BUTTON_2
#define MIST_MOUSE_BUTTON_MIDDLE MIST_MOUSE_BUTTON_3